name: Scrape and update evals database on AWS S3

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: cd backend/web_scraping
      - run: npm ci
      - name: Run update script 
      - run: node main.js
