name: Scrape and update evals database on AWS S3

# TODO: Add chron schedule.
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
        working-directory: backend/web_scraping
      - name: Run update script
        run: node test_auth_main.js
        env:
          SCU_USERNAME: ${{ secrets.SCU_USERNAME }}
          SCU_PASSWORD: ${{ secrets.SCU_PASSWORD }}
        working-directory: backend/web_scraping
